### ISSUE TITLE
[1.14.4] Please update dependency

### ISSUE THREAD

**Issue by ProsperCraft** [Geek202/LookAtThat#1]
**Describe the bug**
![2020-02-16_08 50 17](https://user-images.githubusercontent.com/4427684/74607857-951ac780-5099-11ea-972c-b28433d06399.png)

Forge - 1.14.4 - 28.2.1

**Comment by Tom-The-Geek** [comment]
Made a quick fix on GitHub, however I am away and can't make a build for CurseForge so if you would like to use it on the new version try building it yourself.

**Comment by ProsperCraft** [comment]
Ping me when you push to curseforge and I will add it to my 1.14.4 pack and push, thank you.

**Comment by Tom-The-Geek** [comment]
@ProsperCraft I have pushed the updated 1.14.4 version to CurseForge.
