### ISSUE TITLE
Immersive Portals and Look At That don't play well

### ISSUE THREAD

**Issue by DatrixTHLK** [Geek202/LookAtThat#10]
**Describe the bug**
It appears that Immersive Portals and Look at That don't play well with one another. Looking at a Nether Portal with this mod causes the game to freeze up and crash

**To Reproduce**
1. Go to create a portal
2. Click on portal with flint and steel
3. Look at portal after it activates
4. Game freezes
5. Game crashes shortly after

**Expected behavior**
I expected the game not to crash when looking through a portal with Immersive Portals

**Additional context**
Minecraft 1.15.2
forge: 31.1.18
Look At That: 1.4
MixinBootstrap: 1.0.2
Immersive Portals: 0.6(for mc 1.15 forge)
Crash Log: https://gist.github.com/DatrixTHLK/33dbc9517245eeff640b59f4339bdd06

**Comment by Tom-The-Geek** [comment]
Immersive portals seems to be causing the issue by setting minecraft's objectMouseOver property to null when looking at a portal, instead of RayTraceResult.MISS. LookAtThat only crashes as this is not normal behaviour of Minecraft.

**Comment by DatrixTHLK** [comment]
Well, I have changed that mod for another one called The One Probe. It doesn't crash when looking at a nether portal. Does what I need it to do. Thanks anyways for figuring out what the issue was. I appreciate the response.
