### ISSUE TITLE
1.16.1 - game crash when joining world

### ISSUE THREAD

**Issue by bessiq** [Geek202/LookAtThat#12]
**Describe the bug**
Minecraft: 1.16.1
Forge: 32.0.23
Mod: 1.5-1.16.1

Minecraft crashes when joining a local world with this mod enabled. Here is the crash log:
[https://pastebin.com/c5bAfvrz](https://pastebin.com/c5bAfvrz)

**To Reproduce**
1. Launch Minecraft (modded with Forge)
2. Create new world (default world type)
3. World creation completes at 100%
3. Game window closes right after the log says I've joined the world

**Expected behavior**
Should be able to load into world successfully.

**Screenshots**
n/a

**Additional context**
I am using MultiMC since Forge for 1.16 isn't on the Twitch launcher yet. Let me know if I can provide any other info or test it another way. Thanks!

**Comment by Tom-The-Geek** [comment]
Hello!

Thanks for the report. I will look into this issue tomorrow, when I have more time.

- Tom

**Comment by Tom-The-Geek** [comment]
Quickly checked the log, and I believe [this](https://github.com/Geek202/LookAtThat/blob/1.16/src/main/java/me/geek/tom/lat/overlay/OverlayRenderer.java#L55) is the problematic line, as there is the potential for currentBlockInfo to be null.

**Comment by Tom-The-Geek** [comment]
Hopefully, this should be fixed, I am going to push this to curseforge. Reopen this if it continues to occur.
