### ISSUE TITLE
Missing License Information error on launch

### ISSUE THREAD

**Issue by Murdermancer** [Geek202/LookAtThat#16]
Minecraft crashes during loading with the error:
**Missing License Information in file Mod File: ~ LookAtThat-1.7-1.16.1.jar**

Using Forge 35.1.36, Minecraft 1.16.4 (I realize the mod is for 1.16.1, but this seemed like an odd thing for it to fail on.)

**Comment by Tom-The-Geek** [comment]
You should be able to use this version, which includes the licence field, and is 1.16.2+ compatible: https://www.curseforge.com/minecraft/mc-mods/look-at-that/files/3035358 (I believe CurseForge doesn't show this as the latest because its marked as a beta). Sorry for the confusion!
