### ISSUE TITLE
[1.14.4] [1.15.2] This doesn't work on a dedicated server - nothing shows.

### ISSUE THREAD

**Issue by ProsperCraft** [Geek202/LookAtThat#3]
**Describe the bug**
When on single player, I see the box just fine, I log in to the server and nothing.

I tried putting it on the server but then it crashes due to sidedness.

1.15.2 V1.1
--

Modpack- https://www.curseforge.com/minecraft/modpacks/towncraft  Beta branch for 1.15.2

**Comment by Tom-The-Geek** [comment]
Is there an chance you could attach the game log/crash report as this would help me to locate the bug. Thanks.

**Comment by ProsperCraft** [comment]
I can when I get home, otherwise you can simply run a dedicated server binary on your local machine with only your mod, then connect to it with a client with only your mod, and get a nice clean log.

**Comment by Tom-The-Geek** [comment]
Its alright now, I managed to find the bug yesterday and have found another bug while fixing it that would also cause crashing on a dedicated server.

**Comment by Tom-The-Geek** [comment]
Fixed on 1.15.2 and will upload update to CurseForge soon.
