### ISSUE TITLE
[issue] cosmetic, position of the edit box

### ISSUE THREAD

**Issue by kreezxil** [Geek202/LookAtThat#6]
when you right click to edit the hud sign, have the input box appear in front of  you over the sign. basically in the center of your screen.

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/75467318-16534380-5951-11ea-94e1-89e33a572980.png)

**Comment by Tom-The-Geek** [comment]
That would look better, the current position I just set during setup and never really got changed.
