### ISSUE TITLE
NoSuchMethodError in 1.15.2-1.4 <banners cause crash>

### ISSUE THREAD

**Issue by kreezxil** [Geek202/LookAtThat#7]
woke up to a server crash, don't know what the player was doing at the time:

crash report: 
http://paste.ubuntu.com/p/fxCRtKzcSS/

fml server latest: 
http://paste.ubuntu.com/p/CwFJz5KFYt/

**Comment by Tom-The-Geek** [comment]
It appears that the player looked at a banner and the mod failed to call the function that requests the item for display. Will look into this as it seems to be a big flaw.

**Comment by Tom-The-Geek** [comment]
Have started researching the issue but it seems to be caused by Mojang's ProGuard optimiser removing 'unused' code

**Comment by Tom-The-Geek** [comment]
Implemented temporary fix for this and will push to CurseForge tomorrow.

**Comment by Tom-The-Geek** [comment]
Forge has pushed a commit that fixes this. It has been fixed in 1.15.2-31.2.19
